# Generated by Django 5.2.5 on 2025-08-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='respomse',
            new_name='response',
        ),
    ]
