from rest_framework import serializers
from .models import User,Chat

class UserRegistrationSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ['username', 'password']
        extra_kwargs = {'password': {'write_only': True}}

    def create(self, validated_data):
        #create the user helper function to properly handle password hashing
        user = User.objects.create_user(
            username=validated_data['username'],
            password=validated_data['password'],
        )
        return user
        
class ChatSerializer(serializers.ModelSerializer):
    class Meta:
        model = Chat
        # The user only needs to send a message
        # the response and timestamp will be generated by the server
        fields = ['message','response','timestamp']
        read_only_fields = ['response', 'timestamp']
        
class UserLoginSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ['username', 'password']
        extra_kwargs = {
            'password': {'write_only': True},
            'username': {'write_only': True}
            }